# -*- coding: utf-8 -*-
"""IBM webinar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3XceW2nO3XH_3HeAff9HoXGqxiap9Va
"""

!pip install langchain_community
!pip install replicate

from langchain_community.llms import Replicate
import os
from google.colab import userdata
# Set the API token
api_token = userdata.get('api_token')
os.environ["REPLICATE_API_TOKEN"] = api_token
# Model setup
model = "ibm-granite/granite-3.3-8b-instruct"
output = Replicate(
model=model,
replicate_api_token=api_token,
)

# input prompt
p = input("input prompt?: ")
# run model
response = output.invoke(p)
# show answer
print(response)